config/routes.rb
Rails.application.routes.draw do
  devise_for :receivers, :controllers => {
    registrations: 'receivers/registrations',
    :sessions => 'receivers/sessions',
    :passwords => 'receivers/passwords',
    :confirmations => 'receivers/confirmations'
  }

  authenticate :receiver do
    namespace :receivers do
      resources :organizations, only: [:edit, :update]
      resources :schedules
      resources :receipts
      get '/' => 'dashboards#index'
      root :to => 'dashboards#index'
    end
  end

  devise_for :providers, :controllers => {
    registrations: 'providers/registrations',
    :sessions => "providers/sessions",
    :passwords => 'providers/passwords',
    :confirmations => 'providers/confirmations'
  }

  authenticate :provider do
    namespace :providers do
      resources :providers
      resources :organizations, only: [:edit, :update]
      resources :schedules
      resources :receipts
      match '/notify_receivers' => 'providers#notify_receivers', as: :notify_receivers, via: :all
      get '/' => 'dashboards#index'
      root :to => 'dashboards#index'
    end
  end

  root 'pages#index'
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :receipt
  belongs_to :organization

  attr_accessor :updating_password

  def name
    full_name
  end

  def full_name
    (self.first_name + ' ' + self.last_name).titleize
  end

  def should_validate_password?
    updating_password || new_record?
  end
end

app/controllers/provider_controller.rb
class ProviderController < ApplicationController
  before_filter :authenticate_provider!
  layout 'providers/default'
  before_filter :check_provider_active

  expose(:current_account){
    if current_provider
      current_provider.organization
    end
  }

  private
  def check_provider_active
    unless current_provider.active
      flash[:notice]= t(:provider_not_active)
      sign_out current_provider
      redirect_to new_provider_session_path
    end
  end
end

app/controllers/providers/dashboards_controller.rb
class Providers::DashboardsController < ProviderController

  def index
  end

  private

  def chart
    @chart = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(:text => "Population vs GDP For 5 Big Countries [2009]")
      f.xAxis(:categories => ["United States", "Japan", "China", "Germany", "France"])
      f.series(:name => "GDP in Billions", :yAxis => 0, :data => [14119, 5068, 4985, 3339, 2656])
      f.series(:name => "Population in Millions", :yAxis => 1, :data => [310, 127, 1340, 81, 65])

      f.yAxis [
        {:title => {:text => "GDP in Billions", :margin => 70} },
        {:title => {:text => "Population in Millions"}, :opposite => true},
      ]

      f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
      f.chart({:defaultSeriesType=>"column"})
    end
  end
end

app/controllers/providers/organizations_controller.rb
class Providers::OrganizationsController < ProviderController
  expose(:organization){ current_account }

  def update
    if organization.update_attributes(organization_params)
      flash[:notice] = t(:organization_was_successfully_updated)
      redirect_to providers_root_path
    else
      render :edit
    end
  end

  private

  def organization_params
    params.require(:organization).permit(
      :name,
      :address,
      :city,
      :state,
      :zip,
    )
  end
end

app/controllers/providers/passwords_controller.rb
class Providers::PasswordsController < Devise::PasswordsController
  layout 'layouts/public'

end

app/controllers/providers/providers_controller.rb
class Providers::ProvidersController < ProviderController
  before_filter :check_password_submitted, :only => :update

  expose(:providers){ current_account.providers }
  expose(:provider, attributes: :provider_params)

  def create
    if provider.save
      flash[:notice] = t(:staff_was_successfully_created)
      redirect_to providers_providers_path
    else
      render :new
    end
  end
  def update
    if provider.save
      flash[:notice] = t(:staff_was_successfully_updated)
      redirect_to providers_providers_path
    else
      render :edit
    end
  end

  def notify_receivers
    Sms.send_message('7864495989', 'Food is ready to be pick at.')
    redirect_to :back
  end


  private

  def check_password_submitted
    if params[:provider][:password].blank?
      params[:provider].delete("password")
      provider.updating_password = false
    else
      provider.updating_password = true
    end
  end

  def provider_params
    params.require(:provider).permit(
      :email,
      :first_name,
      :last_name,
      :is_admin,
      :password,
      :password_confirmation,
    )
  end
end

app/controllers/providers/receipts_controller.rb
class Providers::ReceiptsController < ProviderController

  expose(:receipt){ current_account.receipts }
  expose(:receipt, attributes: :receipt_params)

end

app/controllers/providers/registrations_controller.rb
class Providers::RegistrationsController < Devise::RegistrationsController
  layout :choose_layout

  after_filter :add_organisation, only: :create
  def choose_layout
    if params[:action] == 'edit' or params[:action] =='update' or params[:action] =='change_password'
      'providers/default'
    else
     'layouts/public'
    end
  end

  private

  def add_organisation
    organization = Organization.create()
    current_provider.is_owner = true
    current_provider.organization_id = organization.id
    current_provider.save
  end

  def sign_up_params
    allow = [:first_name, :last_name, :email, :password, :password_confirmation]
      params.require(resource_name).permit(allow)
  end
end

app/controllers/providers/schedules_controller.rb
class Providers::SchedulesController < ProviderController

  expose(:schedules){ current_account.schedules }
  expose(:event){
    if params[:action] == 'new'
      current_account.schedules.new()
    elsif params[:action] == 'create'
      Event.new(params[:event])
    elsif params[:action] == 'show' || params[:action] == 'edit'
      Event.find(params[:id])
    end
  }
end

app/controllers/providers/sessions_controller.rb
class Providers::SessionsController < Devise::SessionsController
  layout 'layouts/public'
end

app/views/layouts/providers/default.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %title Food Bank
    = render 'layouts/shared/meta'
    = stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track' => true
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lte IE 8]
      <script src="/assets/html5shiv/html5shiv.js"></script>
      <script src="/assets/plugins/respond/respond.min.js"></script>
      <script src="/assets/plugins/flot/excanvas.min.js"></script>
  %body
    .wrapper
      %aside.social-sidebar
        .social-sidebar-content
          .user
            = image_tag 'avatars/avatar-30.png', alt: 'Julio Marquez', height: '25', width: '25', class: 'avatar'
            %span= current_provider.email
            %i.trigger-user-settings.fa.fa-user{"data-toggle" => "dropdown"}
          .clearfix
          .menu
            .menu-content
              %ul#social-sidebar-menu
                %li{class: "#{'active' if params[:controller] == 'providers/dashboards'}"}
                  = link_to providers_root_path do
                    %i.fa.fa-home
                    %span Dashboard
                %li{class: "#{'active' if params[:controller] == 'providers/organization'}"}
                  = link_to edit_providers_organization_path(current_account) do
                    %i.fa.fa-building-o
                    %span Organization
                %li{class: "#{'active' if params[:controller] == 'providers/providers'}"}
                  = link_to providers_providers_path do
                    %i.fa.fa-users
                    %span Staff
                %li{class: "#{'active' if params[:controller] == 'providers/pickup_schedules'}"}
                  = link_to providers_schedules_path do
                    %i.fa.fa-star
                    %span Pickup Schedules
                %li{class: "#{'active' if params[:controller] == 'providers/notify_receivers'}"}
                  = link_to providers_notify_receivers_path do
                    %i.fa.fa-bell-o
                    %span Notify Receivers
                %li{class: "#{'active' if params[:controller] == 'providers/receipts'}"}
                  = link_to providers_receipts_path do
                    %i.fa.fa-money
                    %span Our Receipts
      %header
        %nav.navbar.navbar-fixed-top.navbar-super.social-navbar{:role => "navigation"}
          .navbar-header
            = link_to providers_root_path, title: 'Provider', class: 'navbar-brand' do
              = image_tag 'logo-white-181.png', alt: 'Provider', height: '25', width: '25', class: 'light'
              = image_tag 'logo-gray-181.png', alt: 'Provider', height: '25', width: '25', class: 'dark'
              %span  Provider
          .navbar-toggle
            %i.fa.fa-align-justify
          %div
            %ul.nav.navbar-nav.navbar-right
              %li.divider-vertical
              %li.dropdown
                %a.dropdown-toggle{"data-delay" => "0", "data-hover" => "dropdown", "data-toggle" => "dropdown", :href => "#"}
                  %i.fa.fa-caret-down.fa-lg
                %ul.dropdown-menu
                  %li
                    %a{:href => "#"}
                      %i.fa.fa-user>
                      My Profile
                  %li
                    = link_to destroy_provider_session_path do
                      %i.fa.fa-sign-out>
                      Log Out
                  %li.divider
                  %li
                    = link_to destroy_provider_session_path do
                      %i.fa.fa-info>
                      Help
      .main
        = yield
      %footer 2015 © FoodBanker
    = render 'layouts/shared/footer'