config/routes.rb
Rails.application.routes.draw do
  devise_for :receivers, :controllers => {
    registrations: 'receivers/registrations',
    :sessions => 'receivers/sessions',
    :passwords => 'receivers/passwords',
    :confirmations => 'receivers/confirmations'
  }

  authenticate :receiver do
    namespace :receivers do
      resources :organizations, only: [:edit, :update]
      resources :schedules
      resources :receipts
      get '/' => 'dashboards#index'
      root :to => 'dashboards#index'
    end
  end

  devise_for :providers, :controllers => {
    registrations: 'providers/registrations',
    :sessions => "providers/sessions",
    :passwords => 'providers/passwords',
    :confirmations => 'providers/confirmations'
  }

  authenticate :provider do
    namespace :providers do
      resources :providers
      resources :organizations, only: [:edit, :update]
      resources :schedules
      resources :receipts
      match '/notify_receivers' => 'providers#notify_receivers', as: :notify_receivers, via: :all
      get '/' => 'dashboards#index'
      root :to => 'dashboards#index'
    end
  end

  root 'pages#index'
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :receipt
  belongs_to :organization

  attr_accessor :updating_password

  def name
    full_name
  end

  def full_name
    (self.first_name + ' ' + self.last_name).titleize
  end

  def should_validate_password?
    updating_password || new_record?
  end
end

app/models/schedule.rb
require 'ice_cube_methods'
class Schedule < ActiveRecord::Base
  include IceCubeMethods
  extend SimpleCalendar
  belongs_to :organization
  belongs_to :calendar
  #attr_accessible :description, :name, :calendar_id
  #attr_accessible :repeats_weekly_each_days_of_the_week_mask, :repeats_monthly_each_days_of_the_month_mask, :repeats_monthly_on_ordinals_mask, :repeats_monthly_on_days_of_the_week_mask, :repeats_yearly_each_months_of_the_year_mask, :repeats_yearly_on_ordinals_mask, :repeats_yearly_on_days_of_the_week_mask
  validates_presence_of :name
  validates_presence_of :calendar_id
  validates_presence_of :from_date
  validates_presence_of :to_date
  validates_presence_of :time_zone
  validates_presence_of :from_time, :if => :not_all_day?
  validates_presence_of :to_time, :if => :not_all_day?
  def color
    if calendar.color
      calendar.color
    else
      'lightblue'
    end
  end
  def not_all_day?
    if is_all_day
      return false
    else
      return true
    end
  end
end

app/controllers/provider_controller.rb
class ProviderController < ApplicationController
  before_filter :authenticate_provider!
  layout 'providers/default'
  before_filter :check_provider_active

  expose(:current_account){
    if current_provider
      current_provider.organization
    end
  }

  private
  def check_provider_active
    unless current_provider.active
      flash[:notice]= t(:provider_not_active)
      sign_out current_provider
      redirect_to new_provider_session_path
    end
  end
end

app/controllers/providers/dashboards_controller.rb
class Providers::DashboardsController < ProviderController

  def index
  end

  private

  def chart
    @chart = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(:text => "Population vs GDP For 5 Big Countries [2009]")
      f.xAxis(:categories => ["United States", "Japan", "China", "Germany", "France"])
      f.series(:name => "GDP in Billions", :yAxis => 0, :data => [14119, 5068, 4985, 3339, 2656])
      f.series(:name => "Population in Millions", :yAxis => 1, :data => [310, 127, 1340, 81, 65])

      f.yAxis [
        {:title => {:text => "GDP in Billions", :margin => 70} },
        {:title => {:text => "Population in Millions"}, :opposite => true},
      ]

      f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
      f.chart({:defaultSeriesType=>"column"})
    end
  end
end

app/controllers/providers/organizations_controller.rb
class Providers::OrganizationsController < ProviderController
  expose(:organization){ current_account }

  def update
    if organization.update_attributes(organization_params)
      flash[:notice] = t(:organization_was_successfully_updated)
      redirect_to providers_root_path
    else
      render :edit
    end
  end

  private

  def organization_params
    params.require(:organization).permit(
      :name,
      :address,
      :city,
      :state,
      :zip,
    )
  end
end

app/controllers/providers/passwords_controller.rb
class Providers::PasswordsController < Devise::PasswordsController
  layout 'layouts/public'

end

app/controllers/providers/providers_controller.rb
class Providers::ProvidersController < ProviderController
  before_filter :check_password_submitted, :only => :update

  expose(:providers){ current_account.providers }
  expose(:provider, attributes: :provider_params)

  def create
    if provider.save
      flash[:notice] = t(:staff_was_successfully_created)
      redirect_to providers_providers_path
    else
      render :new
    end
  end
  def update
    if provider.save
      flash[:notice] = t(:staff_was_successfully_updated)
      redirect_to providers_providers_path
    else
      render :edit
    end
  end

  def notify_receivers
    Sms.send_message('7864495989', 'Food is ready to be pick at.')
    redirect_to :back
  end


  private

  def check_password_submitted
    if params[:provider][:password].blank?
      params[:provider].delete("password")
      provider.updating_password = false
    else
      provider.updating_password = true
    end
  end

  def provider_params
    params.require(:provider).permit(
      :email,
      :first_name,
      :last_name,
      :is_admin,
      :password,
      :password_confirmation,
    )
  end
end

app/controllers/providers/receipts_controller.rb
class Providers::ReceiptsController < ProviderController

  expose(:receipt){ current_account.receipts }
  expose(:receipt, attributes: :receipt_params)

end

app/controllers/providers/registrations_controller.rb
class Providers::RegistrationsController < Devise::RegistrationsController
  layout :choose_layout

  after_filter :add_organisation, only: :create
  def choose_layout
    if params[:action] == 'edit' or params[:action] =='update' or params[:action] =='change_password'
      'providers/default'
    else
     'layouts/public'
    end
  end

  private

  def add_organisation
    organization = Organization.create()
    current_provider.is_owner = true
    current_provider.organization_id = organization.id
    current_provider.save
  end

  def sign_up_params
    allow = [:first_name, :last_name, :email, :password, :password_confirmation]
      params.require(resource_name).permit(allow)
  end
end

app/controllers/providers/schedules_controller.rb
class Providers::SchedulesController < ProviderController

  expose(:schedules){ current_account.schedules }
  expose(:event){
    if params[:action] == 'new'
      current_account.schedules.new()
    elsif params[:action] == 'create'
      Event.new(params[:event])
    elsif params[:action] == 'show' || params[:action] == 'edit'
      Event.find(params[:id])
    end
  }
end

app/controllers/providers/sessions_controller.rb
class Providers::SessionsController < Devise::SessionsController
  layout 'layouts/public'
end

app/views/providers/schedules/_form.html.haml
- start_date = params[:start_date].to_datetime.strftime('%F') if params[:start_date]
- start_time = params[:start_date].to_datetime.strftime('%I:%M %p') if params[:start_date]
- end_time = (params[:start_date].to_datetime + 30.minutes).strftime('%I:%M %p') if params[:start_date]
= bootstrap_form_for [:providers, event], html: {class: 'form-horizontal', novalidate: 'novalidate'} do |f|
  .row
    .col-md-6
      = f.text_field :name, class: 'span5'
      = f.text_area :description, class: 'span5', rows: 5
      = #f.select :location_id, options_from_collection_for_select(Place.all, 'id', 'name', f.object.location_id), include_blank: true
      = #f.select :host_id, options_from_collection_for_select(Place.all, 'id', 'name', f.object.host_id), include_blank: true
      %input{:name => "twitter", :type => "checkbox", :value => "Twitter"} Twitter
      %input{:name => "facebook", :type => "checkbox", :value => "Facebook"} Facebook
      %input{:name => "linkedin", :type => "checkbox", :value => "LinkedIn"} LinkedIn
    .col-md-6
      = f.check_box :is_all_day
      - if params[:start_date]
        = f.text_field :from_date, {style: 'width:auto;', :class => 'datepicker', :value => "#{start_date}"}
      - else
        = f.text_field :from_date, {style: 'width:auto;', :class => 'datepicker'}
      .event_time
        - if params[:start_date]
          = f.text_field :from_time, {style: 'width:auto;', :class => 'timepicker', :value => "#{start_time}"}
        - else
          = f.text_field :from_time, {style: 'width:auto;', :class => 'timepicker'}
      - if params[:start_date]
        = f.text_field :to_date, {style: 'width:auto;', :class => 'datepicker', :value => "#{start_date}"}
      - else
        = f.text_field :to_date, {style: 'width:auto;', :class => 'datepicker'}
      .event_time
        - if params[:start_date]
          = f.text_field :to_time, {style: 'width:auto;', :class => 'timepicker', :value => "#{end_time}"}
        - else
          = f.text_field :to_time, {style: 'width:auto;', :class => 'timepicker'}
      .event_time
        = f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, :default => "Eastern Time (US & Canada)"
      = f.select :repeats, Schedule::RepeatsOptions
      = render partial: 'repeats_daily_options', locals: {f: f}
      = render partial: 'repeats_weekly_options', locals: {f: f}
      = render partial: 'repeats_monthly_options', locals: {f: f}
      = render partial: 'repeats_yearly_options', locals: {f: f}
      #repeats_options.event_option
        = f.select :repeat_ends, Schedule::RepeatEndsOptions
        #event_repeat_ends_on
          = f.date_select :repeat_ends_on, {}, {style: 'width:auto;'}

  .form-actions
    = link_to 'Cancel', root_path, :class => 'btn'
    = f.submit 'Save'
- content_for :first_styles do
  :css
    #repeats_options {display:none;}
    #repeats_daily_options {display:none;}
    #repeats_weekly_options {display:none;}
    #repeats_monthly_options {display:none;}
    #repeats_yearly_options {display:none;}

app/views/providers/schedules/_repeats_daily_options.html.haml
%fieldset{id: 'repeats_daily_options', class: 'event_option'}
  = f.number_field :repeats_every_n_days

app/views/providers/schedules/_repeats_monthly_options.html.haml
%fieldset{ id: 'repeats_monthly_options', class: 'event_option'}
  = f.number_field :repeats_every_n_months
  = f.select :repeats_monthly, Schedule::RepeatMonthlyOptions
  #event_repeats_monthly_each.control-group
    %label.control-label Each
    .controls
      - Schedule::DaysOfTheMonth.each do |day_of_the_month|
        = label_tag "event_repeats_monthly_each_days_of_the_month_#{day_of_the_month}", day_of_the_month, :class => 'checkbox inline' do
          = check_box_tag "event[repeats_monthly_each_days_of_the_month][#{day_of_the_month}]", day_of_the_month, f.object.repeats_monthly_each_days_of_the_month.include?(day_of_the_month), {:name => "event[repeats_monthly_each_days_of_the_month][]"}
          = day_of_the_month
      = hidden_field_tag "event[repeats_monthly_each_days_of_the_month][]", ""
  #event_repeats_monthly_on.control-group
    %label.control-label On the
    .controls
      - Schedule::Ordinals.each_with_index do |ordinal,index|
        = label_tag "event_repeats_monthly_on_ordinals_#{ordinal}", ordinal, :class => 'checkbox inline' do
          = check_box_tag "event[repeats_monthly_on_ordinals][#{ordinal}]", ordinal, f.object.repeats_monthly_on_ordinals.include?(ordinal), {:name => "event[repeats_monthly_on_ordinals][]"}
          = Schedule::HumanOrdinals[index]
      = hidden_field_tag "event[repeats_monthly_on_ordinals][]", ""
      %hr
      - Schedule::DaysOfTheWeek.each do |day_of_the_week|
        = label_tag "event_repeats_monthly_on_days_of_the_week_#{day_of_the_week}", day_of_the_week.humanize, :class => 'checkbox inline' do
          = check_box_tag "event[repeats_monthly_on_days_of_the_week][#{day_of_the_week}]", day_of_the_week, f.object.repeats_monthly_on_days_of_the_week.include?(day_of_the_week), {:name => "event[repeats_monthly_on_days_of_the_week][]"}
          = day_of_the_week.humanize
      = hidden_field_tag "event[repeats_monthly_on_days_of_the_week][]", ""

app/views/providers/schedules/_repeats_weekly_options.html.haml
%fieldset{ id: 'repeats_weekly_options', class: 'event_option'}
  = f.number_field :repeats_every_n_weeks
  .control-group
    %label.control-label Each
    .controls
      - Schedule::DaysOfTheWeek.each do |day_of_the_week|
        = label_tag "event_repeats_weekly_each_days_of_the_week_#{day_of_the_week}", day_of_the_week.humanize, :class => 'checkbox inline' do
          = check_box_tag "event[repeats_weekly_each_days_of_the_week][#{day_of_the_week}]", day_of_the_week, f.object.repeats_weekly_each_days_of_the_week.include?(day_of_the_week), {:name => "event[repeats_weekly_each_days_of_the_week][]"}
          = day_of_the_week.humanize
      = hidden_field_tag "event[repeats_weekly_each_days_of_the_week][]", ""

app/views/providers/schedules/_repeats_yearly_options.html.haml
%fieldset{ id: 'repeats_yearly_options', class: 'event_option'}
  = f.number_field :repeats_every_n_years
  .control-group
    %label.control-label Each
    .controls
      - Schedule::MonthsOfTheYear.each do |month_of_the_year|
        = label_tag "event_repeats_yearly_each_months_of_the_year_#{month_of_the_year}", month_of_the_year.humanize, :class => 'checkbox inline' do
          = check_box_tag "event[repeats_yearly_each_months_of_the_year][#{month_of_the_year}]", month_of_the_year, f.object.repeats_yearly_each_months_of_the_year.include?(month_of_the_year), {:name => "event[repeats_yearly_each_months_of_the_year][]"}
          = month_of_the_year.humanize
      = hidden_field_tag "event[repeats_yearly_each_months_of_the_year][]", ""
  = f.check_box :repeats_yearly_on
  #event_repeats_yearly_on_options.control-group
    %label.control-label On the
    .controls
      - Schedule::Ordinals.each_with_index do |ordinal,index|
        = label_tag "event_repeats_yearly_on_ordinals_#{ordinal}", ordinal, :class => 'checkbox inline' do
          = check_box_tag "event[repeats_yearly_on_ordinals][#{ordinal}]", ordinal, f.object.repeats_yearly_on_ordinals.include?(ordinal), {:name => "event[repeats_yearly_on_ordinals][]"}
          = Schedule::HumanOrdinals[index]
      = hidden_field_tag "event[repeats_yearly_on_ordinals][]", ""
      %hr
      - Schedule::DaysOfTheWeek.each do |day_of_the_week|
        = label_tag "event_repeats_yearly_on_days_of_the_week_#{day_of_the_week}", day_of_the_week.humanize, :class => 'checkbox inline' do
          = check_box_tag "event[repeats_yearly_on_days_of_the_week][#{day_of_the_week}]", day_of_the_week, f.object.repeats_yearly_on_days_of_the_week.include?(day_of_the_week), {:name => "event[repeats_yearly_on_days_of_the_week][]"}
          = day_of_the_week.humanize
      = hidden_field_tag "event[repeats_yearly_on_days_of_the_week][]", ""

app/views/providers/schedules/index.html.haml
.container
  .row
    .col-md-12
      %h3.page-title &nbsp;
.container
  .row
    .col-md-12
      .panel.panel-default
        .panel-heading
          %h3.panel-title Pickup Schedules
        .panel-body
          = link_to 'New Event', new_providers_schedule_path, :class => 'btn btn-primary pull-right'
          %h4
            Currently:
            = Time.now.strftime("%D %r")
          = month_calendar events: schedules do |date, meetings|
            = date.strftime('%d')
            %br
            - if rand(1000) < 200
              Giveing food

app/views/providers/schedules/new.html.haml
.container
  .row
    .col-md-12
      %h3.page-title &nbsp;
.container
  .row
    .col-md-12
      .panel.panel-default
        .panel-heading
          %h3.panel-title Create Pickup
        .panel-body
          = render 'form'