config/routes.rb
Rails.application.routes.draw do
  devise_for :receivers, :controllers => {
    registrations: 'receivers/registrations',
    :sessions => 'receivers/sessions',
    :passwords => 'receivers/passwords',
    :confirmations => 'receivers/confirmations'
  }

  authenticate :receiver do
    namespace :receivers do
      resources :organizations, only: [:edit, :update]
      resources :schedules
      resources :receipts
      get '/' => 'dashboards#index'
      root :to => 'dashboards#index'
    end
  end

  devise_for :providers, :controllers => {
    registrations: 'providers/registrations',
    :sessions => "providers/sessions",
    :passwords => 'providers/passwords',
    :confirmations => 'providers/confirmations'
  }

  authenticate :provider do
    namespace :providers do
      resources :providers
      resources :organizations, only: [:edit, :update]
      resources :schedules
      resources :receipts
      match '/notify_receivers' => 'providers#notify_receivers', as: :notify_receivers, via: :all
      get '/' => 'dashboards#index'
      root :to => 'dashboards#index'
    end
  end

  root 'pages#index'
end

app/models/receiver.rb
class Receiver < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

	has_many :receipt
  belongs_to :organization

  def name
    full_name
  end

  def full_name
    (self.first_name + ' ' + self.last_name).titleize
  end

end

app/controllers/receiver_controller.rb
class ReceiverController < ApplicationController
  before_filter :authenticate_receiver!
  layout 'receivers/default'
  before_filter :check_receiver_active

  expose(:current_account){
    if current_receiver
      current_receiver.organization
    end
  }
  private
  def check_receiver_active
    unless current_receiver.active
      flash[:notice]= t(:receiver_not_active)
      sign_out current_receiver
      redirect_to new_receiver_session_path
    end
  end
end

app/controllers/receivers/dashboards_controller.rb
class Receivers::DashboardsController < ReceiverController

  def index
    @organizations = Organization.all
    @hash = Gmaps4rails.build_markers(@organizations) do |organization, marker|
      marker.lat organization.latitude
      marker.lng organization.longitude
      marker.infowindow organization.name
      marker.title organization.name
      #marker.picture({
      #  :url => "/assets/map-icons/grocery.png",
      #  :width => 36,
      #  :height => 36
      #})
    end
    to_javascript hash: @hash
  end

  private

  def cart
    @chart = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(:text => "Population vs GDP For 5 Big Countries [2009]")
      f.xAxis(:categories => ["United States", "Japan", "China", "Germany", "France"])
      f.series(:name => "GDP in Billions", :yAxis => 0, :data => [14119, 5068, 4985, 3339, 2656])
      f.series(:name => "Population in Millions", :yAxis => 1, :data => [310, 127, 1340, 81, 65])

      f.yAxis [
        {:title => {:text => "GDP in Billions", :margin => 70} },
        {:title => {:text => "Population in Millions"}, :opposite => true},
      ]

      f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
      f.chart({:defaultSeriesType=>"column"})
    end
  end
end

app/controllers/receivers/organizations_controller.rb
class Receivers::OrganizationsController < ReceiverController
  expose(:organization){ current_account }

  def update
    if organization.update_attributes(organization_params)
      flash[:notice] = t(:organization_was_successfully_updated)
      redirect_to receivers_root_path
    else
      render :edit
    end
  end

  private

  def organization_params
    params.require(:organization).permit(
      :name,
      :address,
      :city,
      :state,
      :zip,
    )
  end
end

app/controllers/receivers/passwords_controller.rb
class Receivers::PasswordsController < Devise::PasswordsController
  layout 'layouts/public'

end

app/controllers/receivers/receipts_controller.rb
class Receivers::ReceiptsController < ReceiverController

  expose(:receipt){ current_account.providers }
  expose(:receipt, attributes: :receipt_params)

  def create

    if receipt.save
      flash[:notice] = t(:receipt_was_successfully_created)
      redirect_to receivers_receipts_path
    else
      render :new
    end

  end

  def update
    if receipt.save
      flash[:notice] = t(:receipt_was_successfully_updated)
      redirect_to receivers_receipt_path
    else
      render :edit
    end
  end

end

app/controllers/receivers/registrations_controller.rb
class Receivers::RegistrationsController < Devise::RegistrationsController
  layout :choose_layout

  after_filter :add_organisation, only: :create
  def choose_layout
    if params[:action] == 'edit' or params[:action] =='update' or params[:action] =='change_password'
      'providers/default'
    else
     'layouts/public'
    end
  end

  private

  def add_organisation
    organization = Organization.create()
    current_receiver.is_owner = true
    current_receiver.organization_id = organization.id
    current_receiver.save
  end

  def sign_up_params
    allow = [:first_name, :last_name, :email, :password, :password_confirmation]
      params.require(resource_name).permit(allow)
  end

end

app/controllers/receivers/sessions_controller.rb
class Receivers::SessionsController < Devise::SessionsController
  layout 'layouts/public'
end

app/views/layouts/receivers/default.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %title Food Bank
    = render 'layouts/shared/meta'
    %script{:src => "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry", :type => "text/javascript"}
    %script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}
    = stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track' => true
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lte IE 8]
      <script src="/assets/html5shiv/html5shiv.js"></script>
      <script src="/assets/plugins/respond/respond.min.js"></script>
      <script src="/assets/plugins/flot/excanvas.min.js"></script>
    = csrf_meta_tags
  %body
    .wrapper
      %aside.social-sidebar
        .social-sidebar-content
          .user
            = image_tag 'avatars/avatar-30.png', alt: current_receiver.name, height: '25', width: '25', class: 'avatar'
            %span= current_receiver.name
            %i.trigger-user-settings.fa.fa-user{"data-toggle" => "dropdown"}
          .clearfix
          .menu
            .menu-content
              %ul#social-sidebar-menu
                %li{class: "#{'active' if params[:controller] == 'receivers/dashboards'}"}
                  = link_to receivers_path do
                    %i.fa.fa-home
                    %span Dashboard
                %li{class: "#{'active' if params[:controller] == 'receivers/organizations'}"}
                  = link_to edit_receivers_organization_path(current_account) do
                    %i.fa.fa-building-o
                    %span Organization
                %li{class: "#{'active' if params[:controller] == 'receivers/staffs'}"}
                  = link_to receivers_root_path do
                    %i.fa.fa-users
                    %span Staff
                %li{class: "#{'active' if params[:controller] == 'receivers/dashboards'}"}
                  = link_to receivers_root_path do
                    %i.fa.fa-star
                    %span Pickup Schedules
                %li{class: "#{'active' if params[:controller] == 'receivers/receipts'}"}
                  = link_to receivers_receipts_path do
                    %i.fa.fa-money
                    %span Receipts
      %header
        %nav.navbar.navbar-fixed-top.navbar-super.social-navbar{:role => "navigation"}
          .navbar-header
            %a.navbar-brand{:href => "#home", :title => "Provider"}
              = image_tag 'logo-white-181.png', alt: 'Provider', height: '25', width: '25', class: 'light'
              = image_tag 'logo-gray-181.png', alt: 'Provider', height: '25', width: '25', class: 'dark'
              %span Receiver
          .navbar-toggle
            %i.fa.fa-align-justify
          %div
            %ul.nav.navbar-nav
              %li.dropdown.navbar-super-fw.hidden-xs
            %ul.nav.navbar-nav.navbar-right
              %li.divider-vertical
              %li.dropdown
                %a.dropdown-toggle{"data-delay" => "0", "data-hover" => "dropdown", "data-toggle" => "dropdown", :href => "#"}
                  %i.fa.fa-caret-down.fa-lg
                %ul.dropdown-menu
                  %li
                    %a{:href => "#"}
                      %i.fa.fa-user>
                      My Profile
                  %li
                    %a{:href => "#"}
                      %i.fa.fa-cogs>
                      Settings
                  %li
                    = link_to destroy_receiver_session_path, :class => '', :method => :delete do
                      %i.fa.fa-sign-out>
                      Log Out
                  %li.divider
                  %li
                    %a{:href => "#"}
                      %i.fa.fa-info>
                      Help
            .nav-indicators
      .main
        = yield
      %footer 2015 © FoodBanker
    = render 'layouts/shared/footer'

app/views/layouts/receivers/login.html.haml
= yield